name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftp.techlore.com:21/"
        user: techloreP@techlore.tech
        password: ${{ secrets.FTP_PASSWORD }}
